on:
  push:
    branches:
      - master
    tags:
      - "**"
name: "Automatic Build System"
jobs:
  build:
    name: "Build Kernel"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "Build Kernel Image"
        run: bash build_kernel.sh
